{
 "title": "HOME",
 "time": { "from": "2020-01-29T00:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Mood over time",
   "type": "timeseries",
   "description": "a",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT date, mood_int FROM \"moodDashboard\" LIMIT 50 "
    }
   ]
  },
  { "title": "Mood Pie", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Journal Entry",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 8 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT journal_entry  FROM \"moodDashboard\" ORDER BY date DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Stress Gauge",
   "type": "gauge",
   "description": "Gauge with levels: 1-29 relaxed, 30-59 normal, 60-79 medium, 80-99 high",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT stress FROM \"moodDashboard\" LIMIT 50 "
    }
   ]
  }
 ]
}