{
 "title": "DashBoard",
 "time": { "from": "2018-09-25T12:46:59.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "id", "query": "1" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mood over time",
   "type": "timeseries",
   "description": "a",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT date, mood_int FROM \"moodDashboard\" WHERE user_id = 1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Mood Pie",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \n  moods AS \"Mood\",\n  COUNT(*) AS \"Count\"\nFROM \"moodDashboard\"\nWHERE user_id = 1\nGROUP BY moods\nORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Journal Entry",
   "type": "canvas",
   "description": "a",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT journal_entry  FROM \"moodDashboard\"  WHERE user_id = 1 ORDER BY date DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Stress Gauge",
   "type": "gauge",
   "description": "Gauge with levels: 1-29 relaxed, 30-59 normal, 60-79 medium, 80-99 high",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT stress FROM \"moodDashboard\" WHERE user_id = 1 ORDER BY date DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Streak",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "data": "[8]",
     "parser": "backend",
     "source": "inline",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n  <span style=\"color:#cdcdcd; font-family: 'Bebas Neue'; font-size: 4em;\">\r\n    <a href=\"https://hacksheffield10-production.up.railway.app/home\" style=\"color:#cdcdcd inherit; text-decoration: none;\">\r\n      To Entries\r\n    </a>\r\n  </span>\r\n</div>\r\n"
   }
  }
 ]
}