{
 "title": "somewthing",
 "time": { "from": "2021-02-15T20:05:24.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "id", "query": "1" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mood over time",
   "type": "timeseries",
   "description": "a",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT date, mood_int FROM \"moodDashboard\" WHERE user_id = 1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Mood Pie",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \n  moods AS \"Mood\",\n  COUNT(*) AS \"Count\"\nFROM \"moodDashboard\"\nWHERE user_id = 1\nGROUP BY moods\nORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Streak",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "data": "[5]",
     "parser": "backend",
     "source": "inline",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Journal Entry",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 9 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT journal_entry  FROM \"moodDashboard\"  WHERE user_id = 1 ORDER BY date DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Stress Gauge",
   "type": "gauge",
   "description": "Gauge with levels: 1-29 relaxed, 30-59 normal, 60-79 medium, 80-99 high",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT stress FROM \"moodDashboard\" WHERE user_id = 1 ORDER BY date DESC LIMIT 1"
    }
   ]
  }
 ]
}